### ISSUE TITLE
error please help

### ISSUE THREAD

**Issue by Lilpablo999** [MachineKillin/Email-Account-Generator-Checker#2]
python3 main.py                                                             137 ⨯
sh: 1: cls: not found
Traceback (most recent call last):
  File "/home/lilpablo/Desktop/Email-Account-Generator-Checker/main.py", line 198, in <module>
    main() 
  File "/home/lilpablo/Desktop/Email-Account-Generator-Checker/main.py", line 28, in main
    ctypes.windll.kernel32.SetConsoleTitleW("Valid Email Account Generator")
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by MachineKillin** [comment]
are you using windows? if not that might be the reason.

**Comment by cratetest27-hash** [comment]
does anyone know how to use acc checker working and not working?
